### ISSUE TITLE
sshd unit failures

### ISSUE THREAD

**Issue by Raffo** [zalando-incubator/kubernetes-on-aws#136]
When ssh connection fails, the instance report failed units: 

````
● sshd@x:22-y:z.service    loaded failed failed  OpenSSH per-connection server daemon (y:z)
````

**Comment by hjacobs** [comment]
This is caused by CoreOS using systemd socket activation to start OpenSSH. We have at least two options to get rid of the unit failures:

* change the SSH port to avoid the usual flood of scans: https://coreos.com/os/docs/latest/customizing-sshd.html
* change from socket activation to "always-on" OpenSSH daemon

**Comment by Raffo** [comment]
Or we can just do both, can't we?

**Comment by linki** [comment]
what's the advantage of socket activation?

**Comment by mikkeloscar** [comment]
We don't consider this a problem so will close it.
