### ISSUE TITLE
figure out split of CF template

### ISSUE THREAD

**Issue by linki** [zalando-incubator/kubernetes-on-aws#45]
having the entire cluster (including all pools) in a single CF stack or having different CF stacks for each set of nodes (masters, worker pool 1, worker pool 2...) is a quite fundamental design decision which we should decide in the team. /cc @mikkeloscar @Raffo @szuecs

**Comment by Raffo** [comment]
Separate templates that we build in one so that we know each time what we actually have running in each cluster? It's all about being able to track what we run while we also make sure things are ok to read/maintain, right?

**Comment by szuecs** [comment]
If we would have a service that owns the lifecycle of clusters (similar to lushan), it would be easy to keep track of what CFs are currently running for a cluster.
I think we have to do it for GA.
@Raffo In the end you also now don't really know the state of the clusters, because we change CF frequently.

**Comment by mikkeloscar** [comment]
I like the idea of having a single CF stack template describing an entire cluster but I'm not completely sure of the limitations of this yet.
If having a single stack makes an update of one worker pool (ASG) take longer time, then it's not the way to go for instance.

**Comment by hjacobs** [comment]
Closing this as we have a follow-up issue for supporting node pools: #115
