### ISSUE TITLE
static pods not registered with api server

### ISSUE THREAD

**Issue by linki** [zalando-incubator/kubernetes-on-aws#514]
Since upgrading to kubernetes 1.7 static pods (apiserver, scheduler, ...) cannot be registered with the api server (mirror pods).

```
Jul 28 08:50:47 ip-172-31-16-25.eu-central-1.compute.internal kubelet-wrapper[936]: E0728 08:50:47.537800     936 kubelet.go:1607] Failed creating a mirror pod for "kube-controller-manager-ip-172-31-16-25.eu-central-1.compute.internal_kube-system(35d2d3b729826258ed71101e688b6bf4)": pods "kube-controller-manager-ip-172-31-16-25.eu-central-1.compute.internal" is forbidden: no providers available to validate pod request
Jul 28 08:50:57 ip-172-31-16-25.eu-central-1.compute.internal kubelet-wrapper[936]: E0728 08:50:57.581996     936 kubelet.go:1607] Failed creating a mirror pod for "kube-proxy-ip-172-31-16-25.eu-central-1.compute.internal_kube-system(2908bf33d480a29f35190eda0d4f912b)": pods "kube-proxy-ip-172-31-16-25.eu-central-1.compute.internal" is forbidden: no providers available to validate pod request
```

I think this error usually happended when there's no PSP for the pod. @szuecs can confirm this.

**Comment by szuecs** [comment]
We found out that this error message is coming from PSP matching.

**Comment by linki** [comment]
Rejected here: https://github.com/kubernetes/kubernetes/blob/v1.7.2/plugin/pkg/admission/security/podsecuritypolicy/admission.go#L149

I added `hostIPC: true` to our almighty PSP since its new but still seeing the issue.

**Comment by hjacobs** [comment]
Is this behavior a blocker for us?

**Comment by mikkeloscar** [comment]
> Is this behavior a blocker for us?

Yes, I think this should just work.

And I'm pretty sure the issue is due to users connecting to the unsecured port now go through the authorization part as `user=system:unsecured` with groups `["system:masters","system:authenticated"]` which we don't recognize in the webhook.

Example request from API server to webhook:

```
{"kind":"SubjectAccessReview","apiVersion":"authorization.k8s.io/v1beta1","metadata":{"creationTimestamp":null},"spec":{"resourceAttributes":{"namespace":"kube-system","verb":"use","group":"extensions","resource":"podsecuritypolicies","name":"restricted"},"user":"system:unsecured","group":["system:masters","system:authenticated"]},"status":{"allowed":false}}
```
So it's simply a matter of treating `system:masters` as `Administrator` in the authz part of the webhook.

In the RBAC PR (#467) this is not an issue because users in `system:masters` are given `cluster-admin` permission by default.
