### ISSUE TITLE
Will you outline how kubernetes-on-aws is better/worse/different than kube-aws?

### ISSUE THREAD

**Issue by leecalcote** [zalando-incubator/kubernetes-on-aws#522]
I'm curious as to when a user should choose kubernetes-on-aws vs kube-aws (or other).

**Comment by szuecs** [comment]
@leecalcote thanks for the question.

I think we have to clarify it better in the docs.

Right now this repository is only helpful:

* if you fork it and work based on your repository
* if you want to have a look at a big scale (35 clusters) configuration
* if we want to discuss with the community (for example in sig-aws)

Basically we work with channels dev, alpha, beta (long living git branches which are merged like this PR -> dev -> alpha -> beta). 

The important thing for the community are the ideas how to deal with >10 clusters or what components you should deploy for example kube2iam, default limits, ....
We plan to open our cluster deployment even more, but did not have the time, yet. I would not expect it to happen before Q3 2017.

**Comment by leecalcote** [comment]
@szuecs makes sense. This is helpful. I'm trying to layout a comparison of tooling in this space. What do think? - https://docs.google.com/presentation/d/1wI7ylUpAPbrF8EKSpc4WXAmQ9G6XsUURxrK1h94W_-w/edit?usp=sharing

**Comment by szuecs** [comment]
Nice comparision!

In order to add more insights:

* We are using 3 Cloudformation stacks: cluster ETCD, KubernetesMaster, KubernetesWorker 
* KubernetesWorker is limited to one instance type (right now, planned to change)
* We use CoreOS Container Linux and apply cloud init specific for KubernetesMaster, KubernetesWorker 

Clusters are updated by the cluster-lifecycle-manager, that apply the 3 CF stacks ( etcd-cluster.yaml senza-definition.yaml), change the cloud inits (userdata-master.yaml userdata-worker.yaml), applies everything from cluster/manifests/ folder. If I merge from dev to alpha, all alpha clusters are updated by the cluster-lifecycle-manager.

I think the biggest benefit is that it supports regular updates. It's common to update all clusters weekly, sometimes more often.
