### ISSUE TITLE
CloudFormation Stack Notifications fail on cluster update

### ISSUE THREAD

**Issue by linki** [zalando-incubator/kubernetes-on-aws#538]
Seems like the `cfn-signal.service` fails quite often on workers with:

```console
Aug 22 15:48:42 ip-172-31-x-x.eu-central-1.compute.internal docker[1150]: Status: Downloaded newer image for registry.opensource.zalan.do/teapot/cfn-signal:1.4-4
Aug 22 15:48:43 ip-172-31-x-x.eu-central-1.compute.internal docker[1150]: INFO: Notifying CloudFormation (region: eu-central-1, stack: kube-1, resource: WorkerAutoScaling, status: 0)...
Aug 22 15:48:43 ip-172-31-x-x.eu-central-1.compute.internal docker[1150]: ValidationError: Stack arn:aws:cloudformation:eu-central-1:some-id:stack/kube-1/some-id is in UPDATE_COMPLETE state and cannot be signaled
Aug 22 15:48:43 ip-172-31-x-x.eu-central-1.compute.internal systemd[1]: cfn-signal.service: Main process exited, code=exited, status=1/FAILURE
Aug 22 15:48:43 ip-172-31-x-x.eu-central-1.compute.internal systemd[1]: Failed to start cfn-signal.service.
Aug 22 15:48:43 ip-172-31-x-x.eu-central-1.compute.internal systemd[1]: cfn-signal.service: Unit entered failed state.
Aug 22 15:48:43 ip-172-31-x-x.eu-central-1.compute.internal systemd[1]: cfn-signal.service: Failed with result 'exit-code'.
```

**Comment by hjacobs** [comment]
Yes, that's some annoyance --- the "error" of being in "UPDATE_COMPLETE" status should be ignored in the script, sadly that only works by fuzzy matching the AWS message.

**Comment by mikkeloscar** [comment]
Since we now have the [kube-node-ready service](https://github.com/zalando-incubator/kubernetes-on-aws/blob/dev/cluster/manifests/kube-node-ready/daemonset.yaml) I wonder if we even need the cfn signal anymore?

As far as I understand it's only usable on stack creation, but since we are waiting for the API server to become ready when provisioning a cluster anyway, it doesn't matter if the stack goes into CREATION_COMPLETE state a bit before the nodes are ready.
